name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: purescript-contrib/setup-purescript@main
        with:
          purescript: "0.14.0-rc3"

      - uses: actions/setup-node@v1
        with:
          node-version: "10"

      - name: Install NPM dependencies
        run: npm install

      - name: Build source
        run: npm run-script build

      - name: Run tests
        run: npm run-script test --if-present
